/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AffiliatesKitRouteImport } from './routes/affiliates_.kit'
import { Route as CronGoogleSyncRouteImport } from './routes/cron.google-sync'
import { Route as CronLeadFollowupsRouteImport } from './routes/cron.lead-followups'
import { Route as CronRemindersRouteImport } from './routes/cron.reminders'
import { Route as CronWeeklySummaryRouteImport } from './routes/cron.weekly-summary'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as StartSuccessRouteImport } from './routes/start_.success'
import { Route as StripeWebhookRouteImport } from './routes/stripe.webhook'
import { Route as WebhooksJobberRouteImport } from './routes/webhooks.jobber'
import { Route as WebhooksQuickbooksRouteImport } from './routes/webhooks.quickbooks'
import { Route as WebhooksSquareRouteImport } from './routes/webhooks.square'
import { Route as ApiV1MeRouteImport } from './routes/api.v1.me'
import { Route as ApiV1ReviewRequestsRouteImport } from './routes/api.v1.review-requests'
import { Route as ConnectGoogleCallbackRouteImport } from './routes/connect.google.callback'
import { Route as ConnectGoogleStartRouteImport } from './routes/connect.google.start'
import { Route as ConnectJobberCallbackRouteImport } from './routes/connect.jobber.callback'
import { Route as ConnectJobberStartRouteImport } from './routes/connect.jobber.start'
import { Route as ConnectQuickbooksCallbackRouteImport } from './routes/connect.quickbooks.callback'
import { Route as ConnectQuickbooksDisconnectedRouteImport } from './routes/connect.quickbooks.disconnected'
import { Route as ConnectQuickbooksStartRouteImport } from './routes/connect.quickbooks.start'
import { Route as ConnectSquareCallbackRouteImport } from './routes/connect.square.callback'
import { Route as ConnectSquareStartRouteImport } from './routes/connect.square.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesKitRoute = AffiliatesKitRouteImport.update({
  id: '/affiliates_/kit',
  path: '/affiliates/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const CronGoogleSyncRoute = CronGoogleSyncRouteImport.update({
  id: '/cron/google-sync',
  path: '/cron/google-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const CronLeadFollowupsRoute = CronLeadFollowupsRouteImport.update({
  id: '/cron/lead-followups',
  path: '/cron/lead-followups',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRemindersRoute = CronRemindersRouteImport.update({
  id: '/cron/reminders',
  path: '/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CronWeeklySummaryRoute = CronWeeklySummaryRouteImport.update({
  id: '/cron/weekly-summary',
  path: '/cron/weekly-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StartSuccessRoute = StartSuccessRouteImport.update({
  id: '/start_/success',
  path: '/start/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeWebhookRoute = StripeWebhookRouteImport.update({
  id: '/stripe/webhook',
  path: '/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksJobberRoute = WebhooksJobberRouteImport.update({
  id: '/webhooks/jobber',
  path: '/webhooks/jobber',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksQuickbooksRoute = WebhooksQuickbooksRouteImport.update({
  id: '/webhooks/quickbooks',
  path: '/webhooks/quickbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSquareRoute = WebhooksSquareRouteImport.update({
  id: '/webhooks/square',
  path: '/webhooks/square',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReviewRequestsRoute = ApiV1ReviewRequestsRouteImport.update({
  id: '/api/v1/review-requests',
  path: '/api/v1/review-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGoogleCallbackRoute = ConnectGoogleCallbackRouteImport.update({
  id: '/connect/google/callback',
  path: '/connect/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGoogleStartRoute = ConnectGoogleStartRouteImport.update({
  id: '/connect/google/start',
  path: '/connect/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectJobberCallbackRoute = ConnectJobberCallbackRouteImport.update({
  id: '/connect/jobber/callback',
  path: '/connect/jobber/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectJobberStartRoute = ConnectJobberStartRouteImport.update({
  id: '/connect/jobber/start',
  path: '/connect/jobber/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectQuickbooksCallbackRoute =
  ConnectQuickbooksCallbackRouteImport.update({
    id: '/connect/quickbooks/callback',
    path: '/connect/quickbooks/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectQuickbooksDisconnectedRoute =
  ConnectQuickbooksDisconnectedRouteImport.update({
    id: '/connect/quickbooks/disconnected',
    path: '/connect/quickbooks/disconnected',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectQuickbooksStartRoute = ConnectQuickbooksStartRouteImport.update({
  id: '/connect/quickbooks/start',
  path: '/connect/quickbooks/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSquareCallbackRoute = ConnectSquareCallbackRouteImport.update({
  id: '/connect/square/callback',
  path: '/connect/square/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSquareStartRoute = ConnectSquareStartRouteImport.update({
  id: '/connect/square/start',
  path: '/connect/square/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/affiliates/kit': typeof AffiliatesKitRoute
  '/cron/google-sync': typeof CronGoogleSyncRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/cron/weekly-summary': typeof CronWeeklySummaryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/start/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/quickbooks': typeof WebhooksQuickbooksRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review-requests': typeof ApiV1ReviewRequestsRoute
  '/connect/google/callback': typeof ConnectGoogleCallbackRoute
  '/connect/google/start': typeof ConnectGoogleStartRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/quickbooks/callback': typeof ConnectQuickbooksCallbackRoute
  '/connect/quickbooks/disconnected': typeof ConnectQuickbooksDisconnectedRoute
  '/connect/quickbooks/start': typeof ConnectQuickbooksStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/affiliates/kit': typeof AffiliatesKitRoute
  '/cron/google-sync': typeof CronGoogleSyncRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/cron/weekly-summary': typeof CronWeeklySummaryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/start/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/quickbooks': typeof WebhooksQuickbooksRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review-requests': typeof ApiV1ReviewRequestsRoute
  '/connect/google/callback': typeof ConnectGoogleCallbackRoute
  '/connect/google/start': typeof ConnectGoogleStartRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/quickbooks/callback': typeof ConnectQuickbooksCallbackRoute
  '/connect/quickbooks/disconnected': typeof ConnectQuickbooksDisconnectedRoute
  '/connect/quickbooks/start': typeof ConnectQuickbooksStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/affiliates_/kit': typeof AffiliatesKitRoute
  '/cron/google-sync': typeof CronGoogleSyncRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/cron/weekly-summary': typeof CronWeeklySummaryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/start_/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/quickbooks': typeof WebhooksQuickbooksRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review-requests': typeof ApiV1ReviewRequestsRoute
  '/connect/google/callback': typeof ConnectGoogleCallbackRoute
  '/connect/google/start': typeof ConnectGoogleStartRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/quickbooks/callback': typeof ConnectQuickbooksCallbackRoute
  '/connect/quickbooks/disconnected': typeof ConnectQuickbooksDisconnectedRoute
  '/connect/quickbooks/start': typeof ConnectQuickbooksStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/affiliates/kit'
    | '/cron/google-sync'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/cron/weekly-summary'
    | '/q/$token'
    | '/r/$token'
    | '/start/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/quickbooks'
    | '/webhooks/square'
    | '/api/v1/me'
    | '/api/v1/review-requests'
    | '/connect/google/callback'
    | '/connect/google/start'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/quickbooks/callback'
    | '/connect/quickbooks/disconnected'
    | '/connect/quickbooks/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/affiliates/kit'
    | '/cron/google-sync'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/cron/weekly-summary'
    | '/q/$token'
    | '/r/$token'
    | '/start/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/quickbooks'
    | '/webhooks/square'
    | '/api/v1/me'
    | '/api/v1/review-requests'
    | '/connect/google/callback'
    | '/connect/google/start'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/quickbooks/callback'
    | '/connect/quickbooks/disconnected'
    | '/connect/quickbooks/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/affiliates_/kit'
    | '/cron/google-sync'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/cron/weekly-summary'
    | '/q/$token'
    | '/r/$token'
    | '/start_/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/quickbooks'
    | '/webhooks/square'
    | '/api/v1/me'
    | '/api/v1/review-requests'
    | '/connect/google/callback'
    | '/connect/google/start'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/quickbooks/callback'
    | '/connect/quickbooks/disconnected'
    | '/connect/quickbooks/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AffiliatesKitRoute: typeof AffiliatesKitRoute
  CronGoogleSyncRoute: typeof CronGoogleSyncRoute
  CronLeadFollowupsRoute: typeof CronLeadFollowupsRoute
  CronRemindersRoute: typeof CronRemindersRoute
  CronWeeklySummaryRoute: typeof CronWeeklySummaryRoute
  QTokenRoute: typeof QTokenRoute
  RTokenRoute: typeof RTokenRoute
  StartSuccessRoute: typeof StartSuccessRoute
  StripeWebhookRoute: typeof StripeWebhookRoute
  WebhooksJobberRoute: typeof WebhooksJobberRoute
  WebhooksQuickbooksRoute: typeof WebhooksQuickbooksRoute
  WebhooksSquareRoute: typeof WebhooksSquareRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1ReviewRequestsRoute: typeof ApiV1ReviewRequestsRoute
  ConnectGoogleCallbackRoute: typeof ConnectGoogleCallbackRoute
  ConnectGoogleStartRoute: typeof ConnectGoogleStartRoute
  ConnectJobberCallbackRoute: typeof ConnectJobberCallbackRoute
  ConnectJobberStartRoute: typeof ConnectJobberStartRoute
  ConnectQuickbooksCallbackRoute: typeof ConnectQuickbooksCallbackRoute
  ConnectQuickbooksDisconnectedRoute: typeof ConnectQuickbooksDisconnectedRoute
  ConnectQuickbooksStartRoute: typeof ConnectQuickbooksStartRoute
  ConnectSquareCallbackRoute: typeof ConnectSquareCallbackRoute
  ConnectSquareStartRoute: typeof ConnectSquareStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates_/kit': {
      id: '/affiliates_/kit'
      path: '/affiliates/kit'
      fullPath: '/affiliates/kit'
      preLoaderRoute: typeof AffiliatesKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/google-sync': {
      id: '/cron/google-sync'
      path: '/cron/google-sync'
      fullPath: '/cron/google-sync'
      preLoaderRoute: typeof CronGoogleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/lead-followups': {
      id: '/cron/lead-followups'
      path: '/cron/lead-followups'
      fullPath: '/cron/lead-followups'
      preLoaderRoute: typeof CronLeadFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/reminders': {
      id: '/cron/reminders'
      path: '/cron/reminders'
      fullPath: '/cron/reminders'
      preLoaderRoute: typeof CronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/weekly-summary': {
      id: '/cron/weekly-summary'
      path: '/cron/weekly-summary'
      fullPath: '/cron/weekly-summary'
      preLoaderRoute: typeof CronWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start_/success': {
      id: '/start_/success'
      path: '/start/success'
      fullPath: '/start/success'
      preLoaderRoute: typeof StartSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/webhook': {
      id: '/stripe/webhook'
      path: '/stripe/webhook'
      fullPath: '/stripe/webhook'
      preLoaderRoute: typeof StripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/jobber': {
      id: '/webhooks/jobber'
      path: '/webhooks/jobber'
      fullPath: '/webhooks/jobber'
      preLoaderRoute: typeof WebhooksJobberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/quickbooks': {
      id: '/webhooks/quickbooks'
      path: '/webhooks/quickbooks'
      fullPath: '/webhooks/quickbooks'
      preLoaderRoute: typeof WebhooksQuickbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/square': {
      id: '/webhooks/square'
      path: '/webhooks/square'
      fullPath: '/webhooks/square'
      preLoaderRoute: typeof WebhooksSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/review-requests': {
      id: '/api/v1/review-requests'
      path: '/api/v1/review-requests'
      fullPath: '/api/v1/review-requests'
      preLoaderRoute: typeof ApiV1ReviewRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/google/callback': {
      id: '/connect/google/callback'
      path: '/connect/google/callback'
      fullPath: '/connect/google/callback'
      preLoaderRoute: typeof ConnectGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/google/start': {
      id: '/connect/google/start'
      path: '/connect/google/start'
      fullPath: '/connect/google/start'
      preLoaderRoute: typeof ConnectGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/jobber/callback': {
      id: '/connect/jobber/callback'
      path: '/connect/jobber/callback'
      fullPath: '/connect/jobber/callback'
      preLoaderRoute: typeof ConnectJobberCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/jobber/start': {
      id: '/connect/jobber/start'
      path: '/connect/jobber/start'
      fullPath: '/connect/jobber/start'
      preLoaderRoute: typeof ConnectJobberStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quickbooks/callback': {
      id: '/connect/quickbooks/callback'
      path: '/connect/quickbooks/callback'
      fullPath: '/connect/quickbooks/callback'
      preLoaderRoute: typeof ConnectQuickbooksCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quickbooks/disconnected': {
      id: '/connect/quickbooks/disconnected'
      path: '/connect/quickbooks/disconnected'
      fullPath: '/connect/quickbooks/disconnected'
      preLoaderRoute: typeof ConnectQuickbooksDisconnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quickbooks/start': {
      id: '/connect/quickbooks/start'
      path: '/connect/quickbooks/start'
      fullPath: '/connect/quickbooks/start'
      preLoaderRoute: typeof ConnectQuickbooksStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/square/callback': {
      id: '/connect/square/callback'
      path: '/connect/square/callback'
      fullPath: '/connect/square/callback'
      preLoaderRoute: typeof ConnectSquareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/square/start': {
      id: '/connect/square/start'
      path: '/connect/square/start'
      fullPath: '/connect/square/start'
      preLoaderRoute: typeof ConnectSquareStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AffiliatesKitRoute: AffiliatesKitRoute,
  CronGoogleSyncRoute: CronGoogleSyncRoute,
  CronLeadFollowupsRoute: CronLeadFollowupsRoute,
  CronRemindersRoute: CronRemindersRoute,
  CronWeeklySummaryRoute: CronWeeklySummaryRoute,
  QTokenRoute: QTokenRoute,
  RTokenRoute: RTokenRoute,
  StartSuccessRoute: StartSuccessRoute,
  StripeWebhookRoute: StripeWebhookRoute,
  WebhooksJobberRoute: WebhooksJobberRoute,
  WebhooksQuickbooksRoute: WebhooksQuickbooksRoute,
  WebhooksSquareRoute: WebhooksSquareRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1ReviewRequestsRoute: ApiV1ReviewRequestsRoute,
  ConnectGoogleCallbackRoute: ConnectGoogleCallbackRoute,
  ConnectGoogleStartRoute: ConnectGoogleStartRoute,
  ConnectJobberCallbackRoute: ConnectJobberCallbackRoute,
  ConnectJobberStartRoute: ConnectJobberStartRoute,
  ConnectQuickbooksCallbackRoute: ConnectQuickbooksCallbackRoute,
  ConnectQuickbooksDisconnectedRoute: ConnectQuickbooksDisconnectedRoute,
  ConnectQuickbooksStartRoute: ConnectQuickbooksStartRoute,
  ConnectSquareCallbackRoute: ConnectSquareCallbackRoute,
  ConnectSquareStartRoute: ConnectSquareStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
