/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CronLeadFollowupsRouteImport } from './routes/cron.lead-followups'
import { Route as CronRemindersRouteImport } from './routes/cron.reminders'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as StartSuccessRouteImport } from './routes/start.success'
import { Route as StripeWebhookRouteImport } from './routes/stripe.webhook'
import { Route as WebhooksJobberRouteImport } from './routes/webhooks.jobber'
import { Route as WebhooksSquareRouteImport } from './routes/webhooks.square'
import { Route as ConnectJobberCallbackRouteImport } from './routes/connect.jobber.callback'
import { Route as ConnectJobberStartRouteImport } from './routes/connect.jobber.start'
import { Route as ConnectSquareCallbackRouteImport } from './routes/connect.square.callback'
import { Route as ConnectSquareStartRouteImport } from './routes/connect.square.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CronLeadFollowupsRoute = CronLeadFollowupsRouteImport.update({
  id: '/cron/lead-followups',
  path: '/cron/lead-followups',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRemindersRoute = CronRemindersRouteImport.update({
  id: '/cron/reminders',
  path: '/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StartSuccessRoute = StartSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => StartRoute,
} as any)
const StripeWebhookRoute = StripeWebhookRouteImport.update({
  id: '/stripe/webhook',
  path: '/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksJobberRoute = WebhooksJobberRouteImport.update({
  id: '/webhooks/jobber',
  path: '/webhooks/jobber',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSquareRoute = WebhooksSquareRouteImport.update({
  id: '/webhooks/square',
  path: '/webhooks/square',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectJobberCallbackRoute = ConnectJobberCallbackRouteImport.update({
  id: '/connect/jobber/callback',
  path: '/connect/jobber/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectJobberStartRoute = ConnectJobberStartRouteImport.update({
  id: '/connect/jobber/start',
  path: '/connect/jobber/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSquareCallbackRoute = ConnectSquareCallbackRouteImport.update({
  id: '/connect/square/callback',
  path: '/connect/square/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSquareStartRoute = ConnectSquareStartRouteImport.update({
  id: '/connect/square/start',
  path: '/connect/square/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRouteWithChildren
  '/terms': typeof TermsRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/r/$token': typeof RTokenRoute
  '/start/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRouteWithChildren
  '/terms': typeof TermsRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/r/$token': typeof RTokenRoute
  '/start/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRouteWithChildren
  '/terms': typeof TermsRoute
  '/cron/lead-followups': typeof CronLeadFollowupsRoute
  '/cron/reminders': typeof CronRemindersRoute
  '/r/$token': typeof RTokenRoute
  '/start/success': typeof StartSuccessRoute
  '/stripe/webhook': typeof StripeWebhookRoute
  '/webhooks/jobber': typeof WebhooksJobberRoute
  '/webhooks/square': typeof WebhooksSquareRoute
  '/connect/jobber/callback': typeof ConnectJobberCallbackRoute
  '/connect/jobber/start': typeof ConnectJobberStartRoute
  '/connect/square/callback': typeof ConnectSquareCallbackRoute
  '/connect/square/start': typeof ConnectSquareStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/r/$token'
    | '/start/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/square'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/r/$token'
    | '/start/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/square'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/start'
    | '/terms'
    | '/cron/lead-followups'
    | '/cron/reminders'
    | '/r/$token'
    | '/start/success'
    | '/stripe/webhook'
    | '/webhooks/jobber'
    | '/webhooks/square'
    | '/connect/jobber/callback'
    | '/connect/jobber/start'
    | '/connect/square/callback'
    | '/connect/square/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartRoute: typeof StartRouteWithChildren
  TermsRoute: typeof TermsRoute
  CronLeadFollowupsRoute: typeof CronLeadFollowupsRoute
  CronRemindersRoute: typeof CronRemindersRoute
  RTokenRoute: typeof RTokenRoute
  StripeWebhookRoute: typeof StripeWebhookRoute
  WebhooksJobberRoute: typeof WebhooksJobberRoute
  WebhooksSquareRoute: typeof WebhooksSquareRoute
  ConnectJobberCallbackRoute: typeof ConnectJobberCallbackRoute
  ConnectJobberStartRoute: typeof ConnectJobberStartRoute
  ConnectSquareCallbackRoute: typeof ConnectSquareCallbackRoute
  ConnectSquareStartRoute: typeof ConnectSquareStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/lead-followups': {
      id: '/cron/lead-followups'
      path: '/cron/lead-followups'
      fullPath: '/cron/lead-followups'
      preLoaderRoute: typeof CronLeadFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron/reminders': {
      id: '/cron/reminders'
      path: '/cron/reminders'
      fullPath: '/cron/reminders'
      preLoaderRoute: typeof CronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/success': {
      id: '/start/success'
      path: '/success'
      fullPath: '/start/success'
      preLoaderRoute: typeof StartSuccessRouteImport
      parentRoute: typeof StartRoute
    }
    '/stripe/webhook': {
      id: '/stripe/webhook'
      path: '/stripe/webhook'
      fullPath: '/stripe/webhook'
      preLoaderRoute: typeof StripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/jobber': {
      id: '/webhooks/jobber'
      path: '/webhooks/jobber'
      fullPath: '/webhooks/jobber'
      preLoaderRoute: typeof WebhooksJobberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/square': {
      id: '/webhooks/square'
      path: '/webhooks/square'
      fullPath: '/webhooks/square'
      preLoaderRoute: typeof WebhooksSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/jobber/callback': {
      id: '/connect/jobber/callback'
      path: '/connect/jobber/callback'
      fullPath: '/connect/jobber/callback'
      preLoaderRoute: typeof ConnectJobberCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/jobber/start': {
      id: '/connect/jobber/start'
      path: '/connect/jobber/start'
      fullPath: '/connect/jobber/start'
      preLoaderRoute: typeof ConnectJobberStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/square/callback': {
      id: '/connect/square/callback'
      path: '/connect/square/callback'
      fullPath: '/connect/square/callback'
      preLoaderRoute: typeof ConnectSquareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/square/start': {
      id: '/connect/square/start'
      path: '/connect/square/start'
      fullPath: '/connect/square/start'
      preLoaderRoute: typeof ConnectSquareStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StartRouteChildren {
  StartSuccessRoute: typeof StartSuccessRoute
}

const StartRouteChildren: StartRouteChildren = {
  StartSuccessRoute: StartSuccessRoute,
}

const StartRouteWithChildren = StartRoute._addFileChildren(StartRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartRoute: StartRouteWithChildren,
  TermsRoute: TermsRoute,
  CronLeadFollowupsRoute: CronLeadFollowupsRoute,
  CronRemindersRoute: CronRemindersRoute,
  RTokenRoute: RTokenRoute,
  StripeWebhookRoute: StripeWebhookRoute,
  WebhooksJobberRoute: WebhooksJobberRoute,
  WebhooksSquareRoute: WebhooksSquareRoute,
  ConnectJobberCallbackRoute: ConnectJobberCallbackRoute,
  ConnectJobberStartRoute: ConnectJobberStartRoute,
  ConnectSquareCallbackRoute: ConnectSquareCallbackRoute,
  ConnectSquareStartRoute: ConnectSquareStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
